server:
  port: 8081
---
springbootwebfluxjjwt:
  password:
    encoder:
      secret: ${SECRET}
      iteration: ${ITERATION}
      keylength: ${KEY_LENGTH} 
---
spring:
  profiles: default
  data:
    mongodb:
        uri: mongodb://user-divisa:Rktj11KVEzU1Xrb5@20.114.180.154:27017/divisasdb